version: '3.1'

services:

  postgres:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pagewatchdb
    ports:
      - "5432:5432"
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'


  localstack:
    container_name: localstack
    image: 'localstack/localstack:3.6.0'
    environment:
      - SERVICES=s3
      - HOSTNAME=localstack
    ports:
      - "4566:4566"
      - "8080:8080"
#    volumes:
#      - ./localstack:/tmp/localstack


  s3-setup:
    image: amazon/aws-cli
    depends_on:
      - localstack
    volumes:
      - ./testbucket:/aws
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 10 &&
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket images
      "


volumes:
  postgres_data:
  localstack_data:
